"use node";

import { internalAction } from "../_generated/server";
import type { Id } from "../_generated/dataModel";
import OpenAI from "openai";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { DatabaseClient } from "../../core/db/client.js";

// Lazy initialization of OpenAI client to avoid import-time API key requirement
let openaiClient: OpenAI | null = null;

function getOpenAIClient(): OpenAI {
  if (!openaiClient) {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      throw new Error(
        "OPENAI_API_KEY environment variable is required for summarization"
      );
    }
    openaiClient = new OpenAI({ apiKey });
  }
  return openaiClient;
}

export const run = internalAction({
  handler: async (ctx, { nodeId }: { nodeId: Id<"nodes"> }) => {
    const convexUrl = process.env.CONVEX_URL;
    if (!convexUrl) {
      throw new Error("CONVEX_URL environment variable not set!");
    }
    const db = new DatabaseClient(convexUrl);

    const node = await db.getNode(nodeId);

    if (!node) {
      // TODO: Update node with error state
      console.error(`[Processor:Summarize] Node not found: ${nodeId}`);
      return;
    }

    const { artifactPath, nodeType } = node;

    if (nodeType !== "transcript") {
      // TODO: Update node with error state
      console.error(`[Processor:Summarize] Invalid nodeType: ${nodeType}`);
      return;
    }

    const model = "gpt-4.1";
    const outputPath = artifactPath.replace(
      /\.transcript\.txt$/,
      ".summary.txt"
    );

    try {
      const transcriptContent = readFileSync(artifactPath, "utf-8");

      const systemPrompt = readFileSync(
        join(process.cwd(), "prompts", "summarize.md"),
        "utf-8"
      );

      const userPrompt = `Please summarize this transcript:\n\n${transcriptContent}`;

      const openai = getOpenAIClient();

      const response = await openai.chat.completions.create({
        model: model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.3,
        max_tokens: 2000,
      });

      const summary = response.choices[0]?.message?.content;
      if (!summary) {
        throw new Error("No summary generated by OpenAI");
      }

      writeFileSync(outputPath, summary, "utf-8");

      // Create new node for the summary
      const summaryNodeId = await db.createNode(outputPath, "summary");
      await db.updateNodeState(summaryNodeId, "succeeded");
      await db.createEdge(nodeId, summaryNodeId);
      await db.updateNodeState(nodeId, "succeeded");
    } catch (error) {
      console.error(
        `[Processor:Summarize] Failed to summarize ${artifactPath}:`,
        error
      );
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";
      await db.updateNodeState(nodeId, "failed", errorMessage);
    }
  },
});
