import { readFileSync, writeFileSync } from "node:fs";
import { basename } from "node:path";
import type { Parser } from "../types.js";
import OpenAI from "openai";
import {
  estimateSummarizationCost,
  calculateGPTCost,
  estimateTokenCount,
  formatCost,
} from "../utils/cost-calculator.js";
import { ChatModel } from "openai/resources/shared.mjs";

// Lazy initialization of OpenAI client to avoid import-time API key requirement
let openaiClient: OpenAI | null = null;

function getOpenAIClient(): OpenAI {
  if (!openaiClient) {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      throw new Error(
        "OPENAI_API_KEY environment variable is required for summarization"
      );
    }
    openaiClient = new OpenAI({ apiKey });
  }
  return openaiClient;
}

export const parser: Parser = {
  name: "summarize",
  input: [".transcript.txt", ".combined.transcript.txt"],
  outputExt: ".summary.txt",
  dependsOn: [], // Remove dependency to allow manual selection

  async run(inputPath: string): Promise<string> {
    const outputPath = inputPath.replace(/\.transcript\.txt$/, ".summary.txt");
    const model: ChatModel = "gpt-4.1";

    console.log(`Summarizing transcript: ${basename(inputPath)}`);

    try {
      // Read the transcript content
      const transcriptContent = readFileSync(inputPath, "utf-8");

      // Clean the transcript content to extract the main text
      const lines = transcriptContent.split("\n");
      const contentLines = lines.filter(
        (line) =>
          line.trim() &&
          !line.startsWith("[") &&
          !line.startsWith("===") &&
          !line.startsWith("Transcribed") &&
          !line.startsWith("Audio duration") &&
          !line.includes("DETAILED SEGMENTS")
      );

      const cleanContent = contentLines.join("\n");

      if (!cleanContent.trim()) {
        throw new Error("No meaningful content found in transcript");
      }

      // Calculate estimated cost before making the API call
      const costEstimate = estimateSummarizationCost(cleanContent, model);
      console.log(
        `  Estimated cost: ${formatCost(costEstimate.estimatedCost)} (${costEstimate.estimatedInputTokens} input + ${costEstimate.estimatedOutputTokens} output tokens)`
      );

      // Create the summarization prompt
      const systemPrompt = `You are a professional transcript summarizer, specialized in analyzing creative ideation sessions. Your goal is to extract the most valuable insights, ideas, and potential content seeds from the provided transcript, with a specific focus on identifying questions being asked within the content. Create a comprehensive yet concise summary, focusing on elements that could be developed further. Include:

1.  QUESTIONS BEING ASKED: Identify and list all direct questions, implied questions, or areas of inquiry that the speaker is exploring. This includes rhetorical questions, questions posed to the audience, self-questioning, and any areas where the speaker is seeking answers or solutions. Note the context and significance of each question.
2.  CORE IDEAS / KEY INSIGHTS: Identify the 1-3 most promising or novel ideas, concepts, or significant realizations expressed by the speaker. Focus on what seems new, surprising, or like a potential breakthrough for a creative project.
3.  POTENTIAL SCRIPT/CONTENT FODDER: Extract specific segments, anecdotes, questions raised, or distinct thought threads that could directly inspire or be incorporated into a script or other content. Note *why* it's interesting (e.g., "a strong visual metaphor," "a unique take on X," "a clear problem statement").
4.  POTENTIAL ACTIONABLE NEXT STEPS (if any): List any explicitly stated or strongly implied tasks, research points, or next steps the speaker intends to take *related to the ideas discussed*. Differentiate between general self-talk and concrete intentions.
5.  NOTABLE QUOTES / PHRASES: Significant, memorable, or particularly articulate statements that capture a key thought.
6.  OVERALL THEME/PURPOSE (if discernible): Briefly describe the main underlying goal or theme of the ideation session, even if it's exploratory.`;

      const userPrompt = `Please summarize this transcript:

${cleanContent}`;

      // Get OpenAI client with lazy initialization
      const openai = getOpenAIClient();

      // Call OpenAI API
      console.log(`  Calling ${model} for summarization...`);
      const response = await openai.chat.completions.create({
        model: model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.3, // Lower temperature for more focused summaries
        max_tokens: 2000, // Reasonable limit for summaries
      });

      const summary = response.choices[0]?.message?.content;
      if (!summary) {
        throw new Error("No summary generated by OpenAI");
      }

      // Calculate actual cost based on token usage
      const actualInputTokens =
        response.usage?.prompt_tokens || costEstimate.estimatedInputTokens;
      const actualOutputTokens =
        response.usage?.completion_tokens || costEstimate.estimatedOutputTokens;
      const actualCost = calculateGPTCost(
        actualInputTokens,
        actualOutputTokens,
        model
      );

      console.log(
        `  ✅ Summary generated: ${actualInputTokens} input + ${actualOutputTokens} output tokens`
      );
      console.log(`  💰 Actual cost: ${formatCost(actualCost.totalCost)}`);

      // Create the final output with metadata
      const finalSummary = `SUMMARY OF: ${basename(inputPath)}

Generated by: OpenAI ${model}
Source transcript: ${inputPath}
Generated at: ${new Date().toISOString()}
Processing cost: ${formatCost(actualCost.totalCost)} (${actualInputTokens} input + ${actualOutputTokens} output tokens)
Original content: ${transcriptContent.length} characters, ${contentLines.length} content lines

================================================================================

${summary}

================================================================================

Processing Details:
- Model: ${model}
- Input tokens: ${actualInputTokens}
- Output tokens: ${actualOutputTokens}
- Total cost: ${formatCost(actualCost.totalCost)}
- Processing time: ${new Date().toISOString()}`;

      writeFileSync(outputPath, finalSummary, "utf-8");

      return outputPath;
    } catch (error) {
      console.error(`Failed to summarize ${basename(inputPath)}:`, error);

      // Create error summary
      const errorSummary = `SUMMARY ERROR: ${basename(inputPath)}

Failed to generate AI summary at: ${new Date().toISOString()}
Error: ${error instanceof Error ? error.message : "Unknown error"}
Source transcript: ${inputPath}

The transcript content could not be processed by the AI summarization service.
Please check the transcript content and try again, or process manually.

Generated at: ${new Date().toISOString()}`;

      writeFileSync(outputPath, errorSummary, "utf-8");
      throw error;
    }
  },
};
